datadog:
  dogstatsd:
    useHostPort: true
  apm:
    portEnabled: true

agents:
  containers:
    agent:
      env:
        - name: DD_OTLP_HTTP_PORT
          value: "4318"
        - name: DD_OTLP_GRPC_PORT
          value: "4317"
      ports:
        - containerPort: 4318
          hostPort: 4318
          name: otlphttpport
          protocol: TCP
        - containerPort: 4317
          hostPort: 4317
          name: otlpgrpcport
          protocol: TCP
    traceAgent:
      env:
        - name: DD_OTLP_HTTP_PORT
          value: "4318"
        - name: DD_OTLP_GRPC_PORT
          value: "4317"